[package]
name = "imauth-cli"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "imauth"
path = "src/main.rs"

[dependencies]
imauth-proto = { path = "../imauth-proto" }
tokio = { workspace = true }
tonic = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }
