use crate::domain::session::Cookie;
use crate::ports::repository::CookieRepository;
use crate::Result;
use async_trait::async_trait;
use chrono::DateTime;
use sqlx::PgPool;

pub struct PostgresCookieRepository {
    pool: PgPool,
}

impl PostgresCookieRepository {
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

type CookieRow = (String, String, String, String, Option<i64>, bool, bool);

fn cookie_from_row(row: CookieRow) -> Cookie {
    let (name, value, domain, path, expires, http_only, secure) = row;
    Cookie {
        name,
        value,
        domain,
        path,
        expires: expires.and_then(|ts| DateTime::from_timestamp(ts, 0)),
        http_only,
        secure,
    }
}

#[async_trait]
impl CookieRepository for PostgresCookieRepository {
    async fn save(&self, platform: &str, cookies: &[Cookie]) -> Result<()> {
        if cookies.is_empty() {
            return Ok(());
        }

        let mut tx = self.pool.begin().await?;

        for cookie in cookies {
            let expires = cookie.expires.map(|dt| dt.timestamp());
            sqlx::query(
                r#"
                INSERT INTO cookies (platform, name, value, domain, path, expires, http_only, secure, updated_at)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, EXTRACT(EPOCH FROM NOW())::bigint)
                ON CONFLICT(platform, name, domain) DO UPDATE SET
                    value = excluded.value,
                    path = excluded.path,
                    expires = excluded.expires,
                    http_only = excluded.http_only,
                    secure = excluded.secure,
                    updated_at = EXTRACT(EPOCH FROM NOW())::bigint
                "#,
            )
            .bind(platform)
            .bind(&cookie.name)
            .bind(&cookie.value)
            .bind(&cookie.domain)
            .bind(&cookie.path)
            .bind(expires)
            .bind(cookie.http_only)
            .bind(cookie.secure)
            .execute(&mut *tx)
            .await?;
        }

        tx.commit().await?;
        Ok(())
    }

    async fn get<'a>(
        &'a self,
        platform: &'a str,
        domains: Option<&'a [String]>,
    ) -> Result<Vec<Cookie>> {
        const SELECT: &str =
            "SELECT name, value, domain, path, expires, http_only, secure FROM cookies WHERE platform = $1";

        let rows: Vec<CookieRow> = match domains {
            Some([]) => return Ok(Vec::new()),
            Some(domains) => {
                let placeholders: Vec<String> = (1..=domains.len()).map(|i| format!("${}", i + 1)).collect();
                let query = format!("{} AND domain IN ({})", SELECT, placeholders.join(","));
                let mut q = sqlx::query_as(&query).bind(platform);
                for d in domains {
                    q = q.bind(d);
                }
                q.fetch_all(&self.pool).await?
            }
            None => {
                sqlx::query_as(SELECT)
                    .bind(platform)
                    .fetch_all(&self.pool)
                    .await?
            }
        };

        Ok(rows.into_iter().map(cookie_from_row).collect())
    }

    async fn export_netscape(&self, platform: &str) -> Result<String> {
        let cookies = self.get(platform, None).await?;
        let mut lines = vec![
            "# Netscape HTTP Cookie File".to_string(),
            "# This file was generated by imauth. Edit at your own risk.".to_string(),
        ];

        let flag = |b: bool| if b { "TRUE" } else { "FALSE" };
        for cookie in cookies {
            let expires = cookie.expires.map(|dt| dt.timestamp()).unwrap_or(0);
            let host_only_flag = flag(!cookie.domain.starts_with('.'));
            let secure_flag = flag(cookie.secure);
            lines.push(format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}",
                cookie.domain,
                host_only_flag,
                cookie.path,
                secure_flag,
                expires,
                cookie.name,
                cookie.value,
            ));
        }

        Ok(lines.join("\n"))
    }
}
