# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from imauth.v1 import auth_pb2 as imauth_dot_v1_dot_auth__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in imauth/v1/auth_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_stream(
            "/imauth.v1.AuthService/Login",
            request_serializer=imauth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_auth__pb2.AuthEvent.FromString,
            _registered_method=True,
        )
        self.GetStatus = channel.unary_unary(
            "/imauth.v1.AuthService/GetStatus",
            request_serializer=imauth_dot_v1_dot_auth__pb2.StatusRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_auth__pb2.AuthStatusResponse.FromString,
            _registered_method=True,
        )
        self.Cancel = channel.unary_unary(
            "/imauth.v1.AuthService/Cancel",
            request_serializer=imauth_dot_v1_dot_auth__pb2.CancelRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            _registered_method=True,
        )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Open a browser for the given platform and wait for the user to log in.
        Streams AuthEvents: Loading → WaitingForUser (with viewer_url) → Connected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStatus(self, request, context):
        """현재 세션 상태 조회"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Cancel(self, request, context):
        """세션 취소"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Login": grpc.unary_stream_rpc_method_handler(
            servicer.Login,
            request_deserializer=imauth_dot_v1_dot_auth__pb2.LoginRequest.FromString,
            response_serializer=imauth_dot_v1_dot_auth__pb2.AuthEvent.SerializeToString,
        ),
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=imauth_dot_v1_dot_auth__pb2.StatusRequest.FromString,
            response_serializer=imauth_dot_v1_dot_auth__pb2.AuthStatusResponse.SerializeToString,
        ),
        "Cancel": grpc.unary_unary_rpc_method_handler(
            servicer.Cancel,
            request_deserializer=imauth_dot_v1_dot_auth__pb2.CancelRequest.FromString,
            response_serializer=imauth_dot_v1_dot_auth__pb2.AuthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "imauth.v1.AuthService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("imauth.v1.AuthService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/imauth.v1.AuthService/Login",
            imauth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            imauth_dot_v1_dot_auth__pb2.AuthEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.AuthService/GetStatus",
            imauth_dot_v1_dot_auth__pb2.StatusRequest.SerializeToString,
            imauth_dot_v1_dot_auth__pb2.AuthStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Cancel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.AuthService/Cancel",
            imauth_dot_v1_dot_auth__pb2.CancelRequest.SerializeToString,
            imauth_dot_v1_dot_auth__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
