# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imauth/v1/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "imauth/v1/auth.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from imauth.v1 import common_pb2 as imauth_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14imauth/v1/auth.proto\x12\timauth.v1\x1a\x16imauth/v1/common.proto"A\n\x0cLoginRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.PlatformJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04"\xc1\x01\n\tAuthEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.imauth.v1.AuthStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x16\n\x0erequires_input\x18\x04 \x01(\x08\x12\x12\n\ninput_type\x18\x05 \x01(\t\x12"\n\x07\x63ookies\x18\x06 \x03(\x0b\x32\x11.imauth.v1.Cookie\x12\x12\n\nviewer_url\x18\x08 \x01(\tJ\x04\x08\x07\x10\x08"h\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12"\n\x07\x63ookies\x18\x04 \x03(\x0b\x32\x11.imauth.v1.Cookie"#\n\rStatusRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t"\x8c\x01\n\x12\x41uthStatusResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.imauth.v1.AuthStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x16\n\x0erequires_input\x18\x04 \x01(\x08\x12\x12\n\ninput_type\x18\x05 \x01(\t"#\n\rCancelRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xca\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x17.imauth.v1.LoginRequest\x1a\x14.imauth.v1.AuthEvent0\x01\x12\x44\n\tGetStatus\x12\x18.imauth.v1.StatusRequest\x1a\x1d.imauth.v1.AuthStatusResponse\x12;\n\x06\x43\x61ncel\x12\x18.imauth.v1.CancelRequest\x1a\x17.imauth.v1.AuthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imauth.v1.auth_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LOGINREQUEST"]._serialized_start = 59
    _globals["_LOGINREQUEST"]._serialized_end = 124
    _globals["_AUTHEVENT"]._serialized_start = 127
    _globals["_AUTHEVENT"]._serialized_end = 320
    _globals["_AUTHRESPONSE"]._serialized_start = 322
    _globals["_AUTHRESPONSE"]._serialized_end = 426
    _globals["_STATUSREQUEST"]._serialized_start = 428
    _globals["_STATUSREQUEST"]._serialized_end = 463
    _globals["_AUTHSTATUSRESPONSE"]._serialized_start = 466
    _globals["_AUTHSTATUSRESPONSE"]._serialized_end = 606
    _globals["_CANCELREQUEST"]._serialized_start = 608
    _globals["_CANCELREQUEST"]._serialized_end = 643
    _globals["_AUTHSERVICE"]._serialized_start = 646
    _globals["_AUTHSERVICE"]._serialized_end = 848
# @@protoc_insertion_point(module_scope)
