# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imauth/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "imauth/v1/common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16imauth/v1/common.proto\x12\timauth.v1"w\n\x06\x43ookie\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0f\n\x07\x65xpires\x18\x05 \x01(\x03\x12\x11\n\thttp_only\x18\x06 \x01(\x08\x12\x0e\n\x06secure\x18\x07 \x01(\x08"\x07\n\x05\x45mpty*\x92\x01\n\x08Platform\x12\x18\n\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x16\n\x12PLATFORM_INSTAGRAM\x10\x01\x12\x14\n\x10PLATFORM_THREADS\x10\x02\x12\x12\n\x0ePLATFORM_NAVER\x10\x03\x12\x15\n\x11PLATFORM_NOVELPIA\x10\x04\x12\x13\n\x0fPLATFORM_MUNPIA\x10\x05*\xd9\x01\n\nAuthStatus\x12\x1b\n\x17\x41UTH_STATUS_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41UTH_STATUS_IDLE\x10\x01\x12\x17\n\x13\x41UTH_STATUS_LOADING\x10\x02\x12\x1e\n\x1a\x41UTH_STATUS_AUTHENTICATING\x10\x03\x12 \n\x1c\x41UTH_STATUS_WAITING_FOR_USER\x10\x04\x12\x19\n\x15\x41UTH_STATUS_CONNECTED\x10\x07\x12\x16\n\x12\x41UTH_STATUS_FAILED\x10\x08"\x04\x08\x05\x10\x05"\x04\x08\x06\x10\x06\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imauth.v1.common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PLATFORM"]._serialized_start = 168
    _globals["_PLATFORM"]._serialized_end = 314
    _globals["_AUTHSTATUS"]._serialized_start = 317
    _globals["_AUTHSTATUS"]._serialized_end = 534
    _globals["_COOKIE"]._serialized_start = 37
    _globals["_COOKIE"]._serialized_end = 156
    _globals["_EMPTY"]._serialized_start = 158
    _globals["_EMPTY"]._serialized_end = 165
# @@protoc_insertion_point(module_scope)
