# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imauth/v1/credential.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "imauth/v1/credential.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from imauth.v1 import common_pb2 as imauth_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aimauth/v1/credential.proto\x12\timauth.v1\x1a\x16imauth/v1/common.proto"x\n\x15SaveCredentialRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x14\n\x0ctwofa_method\x18\x04 \x01(\t"=\n\x14GetCredentialRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform"u\n\x0e\x43redentialInfo\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x14\n\x0chas_password\x18\x03 \x01(\x08\x12\x14\n\x0ctwofa_method\x18\x04 \x01(\t"@\n\x17\x44\x65leteCredentialRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform"^\n\x12\x43redentialResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12%\n\x08platform\x18\x02 \x01(\x0e\x32\x13.imauth.v1.Platform\x12\x10\n\x08username\x18\x03 \x01(\t2\xec\x01\n\x11\x43redentialService\x12G\n\x04Save\x12 .imauth.v1.SaveCredentialRequest\x1a\x1d.imauth.v1.CredentialResponse\x12\x41\n\x03Get\x12\x1f.imauth.v1.GetCredentialRequest\x1a\x19.imauth.v1.CredentialInfo\x12K\n\x06\x44\x65lete\x12".imauth.v1.DeleteCredentialRequest\x1a\x1d.imauth.v1.CredentialResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "imauth.v1.credential_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SAVECREDENTIALREQUEST"]._serialized_start = 65
    _globals["_SAVECREDENTIALREQUEST"]._serialized_end = 185
    _globals["_GETCREDENTIALREQUEST"]._serialized_start = 187
    _globals["_GETCREDENTIALREQUEST"]._serialized_end = 248
    _globals["_CREDENTIALINFO"]._serialized_start = 250
    _globals["_CREDENTIALINFO"]._serialized_end = 367
    _globals["_DELETECREDENTIALREQUEST"]._serialized_start = 369
    _globals["_DELETECREDENTIALREQUEST"]._serialized_end = 433
    _globals["_CREDENTIALRESPONSE"]._serialized_start = 435
    _globals["_CREDENTIALRESPONSE"]._serialized_end = 529
    _globals["_CREDENTIALSERVICE"]._serialized_start = 532
    _globals["_CREDENTIALSERVICE"]._serialized_end = 768
# @@protoc_insertion_point(module_scope)
