# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from imauth.v1 import credential_pb2 as imauth_dot_v1_dot_credential__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in imauth/v1/credential_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class CredentialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Save = channel.unary_unary(
            "/imauth.v1.CredentialService/Save",
            request_serializer=imauth_dot_v1_dot_credential__pb2.SaveCredentialRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_credential__pb2.CredentialResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/imauth.v1.CredentialService/Get",
            request_serializer=imauth_dot_v1_dot_credential__pb2.GetCredentialRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_credential__pb2.CredentialInfo.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/imauth.v1.CredentialService/Delete",
            request_serializer=imauth_dot_v1_dot_credential__pb2.DeleteCredentialRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_credential__pb2.CredentialResponse.FromString,
            _registered_method=True,
        )


class CredentialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Save": grpc.unary_unary_rpc_method_handler(
            servicer.Save,
            request_deserializer=imauth_dot_v1_dot_credential__pb2.SaveCredentialRequest.FromString,
            response_serializer=imauth_dot_v1_dot_credential__pb2.CredentialResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=imauth_dot_v1_dot_credential__pb2.GetCredentialRequest.FromString,
            response_serializer=imauth_dot_v1_dot_credential__pb2.CredentialInfo.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=imauth_dot_v1_dot_credential__pb2.DeleteCredentialRequest.FromString,
            response_serializer=imauth_dot_v1_dot_credential__pb2.CredentialResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "imauth.v1.CredentialService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "imauth.v1.CredentialService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CredentialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Save(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.CredentialService/Save",
            imauth_dot_v1_dot_credential__pb2.SaveCredentialRequest.SerializeToString,
            imauth_dot_v1_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.CredentialService/Get",
            imauth_dot_v1_dot_credential__pb2.GetCredentialRequest.SerializeToString,
            imauth_dot_v1_dot_credential__pb2.CredentialInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.CredentialService/Delete",
            imauth_dot_v1_dot_credential__pb2.DeleteCredentialRequest.SerializeToString,
            imauth_dot_v1_dot_credential__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
