# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imauth/v1/session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "imauth/v1/session.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from imauth.v1 import common_pb2 as imauth_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17imauth/v1/session.proto\x12\timauth.v1\x1a\x16imauth/v1/common.proto"K\n\x11GetCookiesRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform\x12\x0f\n\x07\x64omains\x18\x02 \x03(\t"0\n\nCookieList\x12"\n\x07\x63ookies\x18\x01 \x03(\x0b\x32\x11.imauth.v1.Cookie"g\n\x14UpdateCookiesRequest\x12%\n\x08platform\x18\x02 \x01(\x0e\x32\x13.imauth.v1.Platform\x12"\n\x07\x63ookies\x18\x03 \x03(\x0b\x32\x11.imauth.v1.CookieJ\x04\x08\x01\x10\x02"6\n\rExportRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform"!\n\x0eNetscapeExport\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t"8\n\x0fValidateRequest\x12%\n\x08platform\x18\x01 \x01(\x0e\x32\x13.imauth.v1.Platform"R\n\x10ValidationResult\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\x12\x1b\n\x13session_cookie_name\x18\x03 \x01(\t"\x89\x01\n\x13\x43onnectionStatusMap\x12@\n\tplatforms\x18\x01 \x03(\x0b\x32-.imauth.v1.ConnectionStatusMap.PlatformsEntry\x1a\x30\n\x0ePlatformsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x32\xf8\x02\n\x0eSessionService\x12\x41\n\nGetCookies\x12\x1c.imauth.v1.GetCookiesRequest\x1a\x15.imauth.v1.CookieList\x12G\n\rUpdateCookies\x12\x1f.imauth.v1.UpdateCookiesRequest\x1a\x15.imauth.v1.CookieList\x12\x45\n\x0e\x45xportNetscape\x12\x18.imauth.v1.ExportRequest\x1a\x19.imauth.v1.NetscapeExport\x12J\n\x0fValidateSession\x12\x1a.imauth.v1.ValidateRequest\x1a\x1b.imauth.v1.ValidationResult\x12G\n\x13GetConnectionStatus\x12\x10.imauth.v1.Empty\x1a\x1e.imauth.v1.ConnectionStatusMapb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "imauth.v1.session_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CONNECTIONSTATUSMAP_PLATFORMSENTRY"]._loaded_options = None
    _globals["_CONNECTIONSTATUSMAP_PLATFORMSENTRY"]._serialized_options = b"8\001"
    _globals["_GETCOOKIESREQUEST"]._serialized_start = 62
    _globals["_GETCOOKIESREQUEST"]._serialized_end = 137
    _globals["_COOKIELIST"]._serialized_start = 139
    _globals["_COOKIELIST"]._serialized_end = 187
    _globals["_UPDATECOOKIESREQUEST"]._serialized_start = 189
    _globals["_UPDATECOOKIESREQUEST"]._serialized_end = 292
    _globals["_EXPORTREQUEST"]._serialized_start = 294
    _globals["_EXPORTREQUEST"]._serialized_end = 348
    _globals["_NETSCAPEEXPORT"]._serialized_start = 350
    _globals["_NETSCAPEEXPORT"]._serialized_end = 383
    _globals["_VALIDATEREQUEST"]._serialized_start = 385
    _globals["_VALIDATEREQUEST"]._serialized_end = 441
    _globals["_VALIDATIONRESULT"]._serialized_start = 443
    _globals["_VALIDATIONRESULT"]._serialized_end = 525
    _globals["_CONNECTIONSTATUSMAP"]._serialized_start = 528
    _globals["_CONNECTIONSTATUSMAP"]._serialized_end = 665
    _globals["_CONNECTIONSTATUSMAP_PLATFORMSENTRY"]._serialized_start = 617
    _globals["_CONNECTIONSTATUSMAP_PLATFORMSENTRY"]._serialized_end = 665
    _globals["_SESSIONSERVICE"]._serialized_start = 668
    _globals["_SESSIONSERVICE"]._serialized_end = 1044
# @@protoc_insertion_point(module_scope)
