# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from imauth.v1 import common_pb2 as imauth_dot_v1_dot_common__pb2
from imauth.v1 import session_pb2 as imauth_dot_v1_dot_session__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in imauth/v1/session_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCookies = channel.unary_unary(
            "/imauth.v1.SessionService/GetCookies",
            request_serializer=imauth_dot_v1_dot_session__pb2.GetCookiesRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_session__pb2.CookieList.FromString,
            _registered_method=True,
        )
        self.UpdateCookies = channel.unary_unary(
            "/imauth.v1.SessionService/UpdateCookies",
            request_serializer=imauth_dot_v1_dot_session__pb2.UpdateCookiesRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_session__pb2.CookieList.FromString,
            _registered_method=True,
        )
        self.ExportNetscape = channel.unary_unary(
            "/imauth.v1.SessionService/ExportNetscape",
            request_serializer=imauth_dot_v1_dot_session__pb2.ExportRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_session__pb2.NetscapeExport.FromString,
            _registered_method=True,
        )
        self.ValidateSession = channel.unary_unary(
            "/imauth.v1.SessionService/ValidateSession",
            request_serializer=imauth_dot_v1_dot_session__pb2.ValidateRequest.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_session__pb2.ValidationResult.FromString,
            _registered_method=True,
        )
        self.GetConnectionStatus = channel.unary_unary(
            "/imauth.v1.SessionService/GetConnectionStatus",
            request_serializer=imauth_dot_v1_dot_common__pb2.Empty.SerializeToString,
            response_deserializer=imauth_dot_v1_dot_session__pb2.ConnectionStatusMap.FromString,
            _registered_method=True,
        )


class SessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCookies(self, request, context):
        """저장된 쿠키 조회"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateCookies(self, request, context):
        """쿠키 업데이트/추가"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExportNetscape(self, request, context):
        """Netscape 포맷으로 쿠키 내보내기"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateSession(self, request, context):
        """세션 쿠키 유효성 검증"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetConnectionStatus(self, request, context):
        """플랫폼별 연결 상태 조회"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetCookies": grpc.unary_unary_rpc_method_handler(
            servicer.GetCookies,
            request_deserializer=imauth_dot_v1_dot_session__pb2.GetCookiesRequest.FromString,
            response_serializer=imauth_dot_v1_dot_session__pb2.CookieList.SerializeToString,
        ),
        "UpdateCookies": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateCookies,
            request_deserializer=imauth_dot_v1_dot_session__pb2.UpdateCookiesRequest.FromString,
            response_serializer=imauth_dot_v1_dot_session__pb2.CookieList.SerializeToString,
        ),
        "ExportNetscape": grpc.unary_unary_rpc_method_handler(
            servicer.ExportNetscape,
            request_deserializer=imauth_dot_v1_dot_session__pb2.ExportRequest.FromString,
            response_serializer=imauth_dot_v1_dot_session__pb2.NetscapeExport.SerializeToString,
        ),
        "ValidateSession": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateSession,
            request_deserializer=imauth_dot_v1_dot_session__pb2.ValidateRequest.FromString,
            response_serializer=imauth_dot_v1_dot_session__pb2.ValidationResult.SerializeToString,
        ),
        "GetConnectionStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetConnectionStatus,
            request_deserializer=imauth_dot_v1_dot_common__pb2.Empty.FromString,
            response_serializer=imauth_dot_v1_dot_session__pb2.ConnectionStatusMap.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "imauth.v1.SessionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "imauth.v1.SessionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCookies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.SessionService/GetCookies",
            imauth_dot_v1_dot_session__pb2.GetCookiesRequest.SerializeToString,
            imauth_dot_v1_dot_session__pb2.CookieList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateCookies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.SessionService/UpdateCookies",
            imauth_dot_v1_dot_session__pb2.UpdateCookiesRequest.SerializeToString,
            imauth_dot_v1_dot_session__pb2.CookieList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExportNetscape(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.SessionService/ExportNetscape",
            imauth_dot_v1_dot_session__pb2.ExportRequest.SerializeToString,
            imauth_dot_v1_dot_session__pb2.NetscapeExport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.SessionService/ValidateSession",
            imauth_dot_v1_dot_session__pb2.ValidateRequest.SerializeToString,
            imauth_dot_v1_dot_session__pb2.ValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetConnectionStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/imauth.v1.SessionService/GetConnectionStatus",
            imauth_dot_v1_dot_common__pb2.Empty.SerializeToString,
            imauth_dot_v1_dot_session__pb2.ConnectionStatusMap.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
