use super::state::Cookie;
use crate::ImauthError;
use sqlx::SqlitePool;

pub struct CookieJar {
    pool: SqlitePool,
}

impl CookieJar {
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    pub async fn init(&self) -> crate::Result<()> {
        sqlx::query(
            r#"
            CREATE TABLE IF NOT EXISTS cookies (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                platform TEXT NOT NULL,
                name TEXT NOT NULL,
                value TEXT NOT NULL,
                domain TEXT NOT NULL,
                path TEXT NOT NULL DEFAULT '/',
                expires INTEGER,
                http_only INTEGER NOT NULL DEFAULT 0,
                secure INTEGER NOT NULL DEFAULT 0,
                created_at INTEGER NOT NULL DEFAULT (unixepoch()),
                updated_at INTEGER NOT NULL DEFAULT (unixepoch()),
                UNIQUE(platform, name, domain)
            );
            CREATE INDEX IF NOT EXISTS idx_cookies_platform ON cookies(platform);
            CREATE INDEX IF NOT EXISTS idx_cookies_domain ON cookies(domain);
            "#,
        )
        .execute(&self.pool)
        .await
        .map_err(|e| ImauthError::Database(e.to_string()))?;
        Ok(())
    }

    pub async fn save(&self, platform: &str, cookies: &[Cookie]) -> crate::Result<()> {
        if cookies.is_empty() {
            return Ok(());
        }

        let mut tx = self
            .pool
            .begin()
            .await
            .map_err(|e| ImauthError::Database(e.to_string()))?;

        for cookie in cookies {
            let expires = cookie.expires.map(|dt| dt.timestamp());
            sqlx::query(
                r#"
                INSERT INTO cookies (platform, name, value, domain, path, expires, http_only, secure, updated_at)
                VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, unixepoch())
                ON CONFLICT(platform, name, domain) DO UPDATE SET
                    value = excluded.value,
                    path = excluded.path,
                    expires = excluded.expires,
                    http_only = excluded.http_only,
                    secure = excluded.secure,
                    updated_at = unixepoch()
                "#,
            )
            .bind(platform)
            .bind(&cookie.name)
            .bind(&cookie.value)
            .bind(&cookie.domain)
            .bind(&cookie.path)
            .bind(expires)
            .bind(cookie.http_only as i32)
            .bind(cookie.secure as i32)
            .execute(&mut *tx)
            .await
            .map_err(|e| ImauthError::Database(e.to_string()))?;
        }

        tx.commit()
            .await
            .map_err(|e| ImauthError::Database(e.to_string()))?;
        Ok(())
    }

    pub async fn get(
        &self,
        platform: &str,
        domains: Option<&[&str]>,
    ) -> crate::Result<Vec<Cookie>> {
        let rows = if let Some(domains) = domains {
            let placeholders = domains.iter().map(|_| "?").collect::<Vec<_>>().join(",");
            let query = format!(
                "SELECT name, value, domain, path, expires, http_only, secure FROM cookies WHERE platform = ? AND domain IN ({})",
                placeholders
            );
            let mut q = sqlx::query_as::<_, (String, String, String, String, Option<i64>, i32, i32)>(
                &query,
            );
            q = q.bind(platform);
            for d in domains {
                q = q.bind(d);
            }
            q.fetch_all(&self.pool).await
        } else {
            sqlx::query_as::<_, (String, String, String, String, Option<i64>, i32, i32)>(
                "SELECT name, value, domain, path, expires, http_only, secure FROM cookies WHERE platform = ?"
            )
            .bind(platform)
            .fetch_all(&self.pool)
            .await
        };

        rows.map_err(|e| ImauthError::Database(e.to_string()))
            .map(|rows| {
                rows.into_iter()
                    .map(
                        |(name, value, domain, path, expires, http_only, secure)| Cookie {
                            name,
                            value,
                            domain,
                            path,
                            expires: expires.and_then(|ts| chrono::DateTime::from_timestamp(ts, 0)),
                            http_only: http_only != 0,
                            secure: secure != 0,
                        },
                    )
                    .collect()
            })
    }

    pub async fn export_netscape(&self, platform: &str) -> crate::Result<String> {
        let cookies = self.get(platform, None).await?;
        let mut lines = vec![
            "# Netscape HTTP Cookie File".to_string(),
            "# This file was generated by imauth. Edit at your own risk.".to_string(),
        ];

        for cookie in cookies {
            let host_only = !cookie.domain.starts_with('.');
            let expires = cookie.expires.map(|dt| dt.timestamp()).unwrap_or(0);
            lines.push(format!(
                "{domain}\t{host_only}\t{path}\t{secure}\t{expires}\t{name}\t{value}",
                domain = cookie.domain,
                host_only = if host_only { "TRUE" } else { "FALSE" },
                path = cookie.path,
                secure = if cookie.secure { "TRUE" } else { "FALSE" },
                expires = expires,
                name = cookie.name,
                value = cookie.value,
            ));
        }

        Ok(lines.join("\n"))
    }
}
